import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1788493097955 implements MigrationInterface {
    name = 'InitialSchema1788493097955'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "forms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "level" integer NOT NULL, CONSTRAINT "PK_ba062fd30b06814a60756f233da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."exam_types_code_enum" AS ENUM('continuous', 'mid_term', 'end_of_term', 'final')`);
        await queryRunner.query(`CREATE TABLE "exam_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" "public"."exam_types_code_enum" NOT NULL, "maxMarks" numeric(5,2) NOT NULL DEFAULT '100', "weight" numeric(5,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_aa2897f3176ef22cc87e38224cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school_years" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isCurrent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3fe99d570a61178cb99065783cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "terms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "termNumber" integer NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isCurrent" boolean NOT NULL DEFAULT false, "schoolYearId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_33b6fe77d6ace7ff43cc8a65958" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employeeNumber" character varying NOT NULL, "title" character varying(16), "gender" character varying(16), "userId" uuid NOT NULL, "department" character varying, "qualification" character varying, "hireDate" date, "isActive" boolean NOT NULL DEFAULT true, "maxWeeklyPeriods" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b3c8cecc83798b429461851ed9d" UNIQUE ("employeeNumber"), CONSTRAINT "REL_eba76c23bcfc9dad2479b7fd2a" UNIQUE ("userId"), CONSTRAINT "PK_e4ee98bb552756c180aec1e854a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exam_marks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "subjectId" uuid NOT NULL, "examTypeId" uuid NOT NULL, "termId" uuid NOT NULL, "classId" uuid NOT NULL, "marks" numeric(6,2) NOT NULL, "grade" character varying, "remarks" character varying, "enteredById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fa578348716d78bb260aea3587a" UNIQUE ("studentId", "subjectId", "examTypeId", "termId"), CONSTRAINT "PK_5fe7a30b91652e8af8e256d0bbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "short" character varying(16), "description" character varying, CONSTRAINT "UQ_542cbba74dde3c82ab49c573109" UNIQUE ("code"), CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_subjects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "subjectId" uuid NOT NULL, "teacherId" uuid, "weeklyPeriods" integer NOT NULL DEFAULT '0', "lessonLength" character varying(16) NOT NULL DEFAULT 'single', CONSTRAINT "UQ_197c3ab1f33416d9c58e636717e" UNIQUE ("classId", "subjectId"), CONSTRAINT "PK_4e1ecabd8771166a29291dc09ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying, "formId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f9749dd3bffd880a497d007e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "formId" uuid NOT NULL, "sectionId" uuid, "classTeacherId" uuid, "capacity" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "occupation" character varying, "gender" character varying(16), "address" character varying, "receivesWhatsApp" boolean NOT NULL DEFAULT true, CONSTRAINT "REL_f1e08daeefd9c2e5def5746be7" UNIQUE ("userId"), CONSTRAINT "PK_9a4dc67c7b8e6a9cb918938d353" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "guardians" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "parentId" uuid, "fullName" character varying, "relationship" character varying, "phone" character varying, "guardianPhone" character varying, "guardianWhatsappConsent" boolean NOT NULL DEFAULT false, "email" character varying, "address" character varying, "isPrimary" boolean NOT NULL DEFAULT false, "isEmergencyContact" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_3dcf02f3dc96a2c017106f280be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."student_attendance_status_enum" AS ENUM('present', 'absent', 'late', 'excused')`);
        await queryRunner.query(`CREATE TYPE "public"."student_attendance_mode_enum" AS ENUM('in_person', 'remote')`);
        await queryRunner.query(`CREATE TABLE "student_attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "date" date NOT NULL, "status" "public"."student_attendance_status_enum" NOT NULL, "mode" "public"."student_attendance_mode_enum" NOT NULL DEFAULT 'in_person', "markedById" character varying, "remarks" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2b9520face75aceadd7d17f739d" UNIQUE ("studentId", "date"), CONSTRAINT "PK_432904873d2981c3443763ef49d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "description" character varying NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unitPrice" numeric(12,2) NOT NULL, "amount" numeric(12,2) NOT NULL, CONSTRAINT "PK_3d18eb48142b916f581f0c21a65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "receipts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "receiptNumber" character varying NOT NULL, "paymentId" uuid NOT NULL, "pdfPath" character varying, "emailedToParent" boolean NOT NULL DEFAULT false, "issuedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae91d6f7ca67ed5bf73177430d7" UNIQUE ("receiptNumber"), CONSTRAINT "REL_1a1d2f3a4c9d21b263ca8ff63e" UNIQUE ("paymentId"), CONSTRAINT "PK_5e8182d7c29e023da6e1ff33bfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('cash', 'bank', 'ecocash', 'onemoney', 'innbucks', 'other')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paymentReference" character varying NOT NULL, "studentId" uuid NOT NULL, "invoiceId" uuid, "amount" numeric(12,2) NOT NULL, "method" "public"."payments_method_enum" NOT NULL, "feeType" character varying(64) NOT NULL DEFAULT 'other', "label" character varying NOT NULL, "notes" character varying, "recordedById" uuid, "paidAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_609e73477743140ae29ae6de486" UNIQUE ("paymentReference"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'sent', 'partial', 'paid', 'overdue', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceNumber" character varying NOT NULL, "studentId" uuid NOT NULL, "termId" uuid, "feeType" character varying(64) NOT NULL DEFAULT 'other', "description" character varying NOT NULL, "totalAmount" numeric(12,2) NOT NULL, "amountPaid" numeric(12,2) NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'sent', "dueDate" date NOT NULL, "issuedDate" date, "pdfPath" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bf8e0f9dd4558ef209ec111782d" UNIQUE ("invoiceNumber"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "termId" uuid, "entryDate" date NOT NULL, "description" character varying NOT NULL, "debit" numeric(12,2) NOT NULL DEFAULT '0', "credit" numeric(12,2) NOT NULL DEFAULT '0', "balance" numeric(12,2) NOT NULL, "referenceType" character varying, "referenceId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6efcb84411d3f08b08450ae75d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admissionNumber" character varying NOT NULL, "userId" uuid, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "dateOfBirth" date, "gender" character varying, "studentType" character varying(32) NOT NULL DEFAULT 'day_scholar', "address" character varying, "previousSchool" character varying, "photoUrl" character varying, "classId" uuid, "formId" uuid, "isActive" boolean NOT NULL DEFAULT true, "status" character varying(24) NOT NULL DEFAULT 'active', "exitDate" date, "exitReason" character varying(255), "enrollmentDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4c256c094ed2d72b3794e4fea86" UNIQUE ("admissionNumber"), CONSTRAINT "REL_e0208b4f964e609959aff431bf" UNIQUE ("userId"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."school_roles_baserole_enum" AS ENUM('director', 'principal', 'admin', 'accountant', 'teacher', 'parent', 'student')`);
        await queryRunner.query(`CREATE TABLE "school_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "baseRole" "public"."school_roles_baserole_enum" NOT NULL, "permissions" text NOT NULL DEFAULT '', "isSystem" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b43717e8ce4be8ca4f384b66491" UNIQUE ("name"), CONSTRAINT "PK_2ca0570efe3bdb508081317e1d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('director', 'principal', 'admin', 'accountant', 'teacher', 'parent', 'student')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "username" character varying, "passwordHash" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "phone" character varying, "role" "public"."users_role_enum" NOT NULL, "schoolRoleId" uuid, "isActive" boolean NOT NULL DEFAULT true, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP WITH TIME ZONE, "passwordResetTokenHash" character varying, "passwordResetExpires" TIMESTAMP WITH TIME ZONE, "avatarUrl" character varying, "portalPasswordCustomized" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_91fddbe23e927e1e525c152baa3" UNIQUE ("code"), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timetables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "dayOfWeek" integer NOT NULL, "startTime" character varying NOT NULL, "endTime" character varying NOT NULL, "subjectId" uuid NOT NULL, "teacherId" uuid, "room" character varying, "isLocked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_9dd7e50645bff59e9ac5b4725c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timetable_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teacherAssignmentId" uuid NOT NULL, "timetableEntryId" uuid, "dayOfWeek" character varying(16) NOT NULL, "periodNumber" integer NOT NULL, "startTime" character varying(8) NOT NULL, "endTime" character varying(8) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2253a56b9d36d00f84aff7efcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teacher_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teacherId" uuid NOT NULL, "classId" uuid NOT NULL, "sectionId" uuid, "subjectId" uuid, "role" character varying(32) NOT NULL, "startDate" date NOT NULL, "endDate" date, "isActive" boolean NOT NULL DEFAULT true, "weeklyPeriods" integer NOT NULL DEFAULT '0', "lessonLength" character varying(16) NOT NULL DEFAULT 'single', "isSharedSplit" boolean NOT NULL DEFAULT false, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_49fabd5cfe8fa2beb47a0b0fed9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."staff_attendance_status_enum" AS ENUM('present', 'absent', 'late', 'excused')`);
        await queryRunner.query(`CREATE TABLE "staff_attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "staffId" uuid NOT NULL, "date" date NOT NULL, "status" "public"."staff_attendance_status_enum" NOT NULL, "markedById" character varying, "remarks" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f0f5b459e3823b7ac9bfe666916" UNIQUE ("staffId", "date"), CONSTRAINT "PK_b76740885e2e06ab5e81ccd7781" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "termId" uuid NOT NULL, "examTypeId" uuid, "subjectResults" jsonb NOT NULL, "averageMark" numeric(6,2), "overallGrade" character varying, "classPosition" integer, "formPosition" integer, "classTotal" integer, "formTotal" integer, "subjectsPassed" integer, "totalSubjects" integer, "classTeacherRemarks" character varying, "principalRemarks" character varying, "behaviorRating" character varying(32), "attitudeRating" character varying(32), "conduct" character varying, "isPublished" boolean NOT NULL DEFAULT false, "pdfUrl" character varying, "generatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e634345d63bafc9a9d745ae7011" UNIQUE ("studentId", "termId", "examTypeId"), CONSTRAINT "PK_ad580db1af279fb14a78f4eb274" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "honour_rolls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "termId" uuid NOT NULL, "classId" uuid, "averageMark" numeric(6,2) NOT NULL, "classPosition" integer NOT NULL, "formPosition" integer NOT NULL, "overallRank" integer NOT NULL, "award" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5f130b295d058834cc79ef7700d" UNIQUE ("studentId", "termId"), CONSTRAINT "PK_04ff93b5778cfccf6de45c50449" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cashbook_entries_type_enum" AS ENUM('receipt', 'payment', 'transfer')`);
        await queryRunner.query(`CREATE TYPE "public"."cashbook_entries_paymentmethod_enum" AS ENUM('cash', 'bank', 'ecocash', 'onemoney', 'innbucks', 'other')`);
        await queryRunner.query(`CREATE TABLE "cashbook_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entryDate" date NOT NULL, "type" "public"."cashbook_entries_type_enum" NOT NULL, "description" character varying NOT NULL, "moneyIn" numeric(12,2) NOT NULL DEFAULT '0', "moneyOut" numeric(12,2) NOT NULL DEFAULT '0', "balance" numeric(12,2) NOT NULL, "paymentMethod" "public"."cashbook_entries_paymentmethod_enum", "reference" character varying, "studentId" character varying, "recordedById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f4e09859dfac7350631af4efa1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."teacher_allocations_dayofweek_enum" AS ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')`);
        await queryRunner.query(`CREATE TABLE "teacher_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timetableEntryId" uuid NOT NULL, "teacherId" uuid NOT NULL, "subjectId" uuid NOT NULL, "classId" uuid NOT NULL, "dayOfWeek" "public"."teacher_allocations_dayofweek_enum" NOT NULL, "startTime" character varying(8) NOT NULL, "endTime" character varying(8) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_teacher_allocations_timetable_entry" UNIQUE ("timetableEntryId"), CONSTRAINT "PK_4a8966c41d32bab4837f2fcd2fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "learning_schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "subjectId" uuid NOT NULL, "termId" uuid NOT NULL, "weekStart" date NOT NULL, "weekEnd" date NOT NULL, "topics" text NOT NULL, "objectives" text, "resources" text, "teacherId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57a670f4693b6bb64ad9183840b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "weekly_assessments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "subjectId" uuid NOT NULL, "termId" uuid NOT NULL, "weekStart" date NOT NULL, "topic" character varying NOT NULL, "score" numeric(6,2), "maxScore" numeric(6,2), "remarks" character varying, "teacherId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e97b5b74c8619fbfee9606df68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "messageId" uuid NOT NULL, "originalName" character varying NOT NULL, "storedName" character varying NOT NULL, "mimeType" character varying NOT NULL, "sizeBytes" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e5085d973567c61e9306f10f95b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "threadId" character varying(128), "senderId" uuid NOT NULL, "recipientId" uuid NOT NULL, "studentId" uuid, "subject" character varying NOT NULL, "body" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "sentAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_15f9bd2bf472ff12b6ee20012d" ON "messages"  ("threadId") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "title" character varying NOT NULL, "message" text NOT NULL, "type" character varying NOT NULL, "metadata" jsonb, "isRead" boolean NOT NULL DEFAULT false, "sentViaWhatsApp" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tuckshop_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "sku" character varying, "unitPrice" numeric(10,2) NOT NULL, "stockQuantity" integer NOT NULL DEFAULT '0', "reorderLevel" integer NOT NULL DEFAULT '10', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_201a34cd4e98088cae31e6bdde6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tuckshop_sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid, "itemId" uuid NOT NULL, "quantity" integer NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "soldAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c36ec1b8c3b45a5a3af8f6461d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "uniform_sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "itemDescription" character varying NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unitPrice" numeric(10,2) NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "invoiceId" character varying, "soldAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d0d2b79f5bf3565c340a55d2cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school_settings" ("id" character varying(32) NOT NULL DEFAULT 'default', "schoolName" character varying NOT NULL DEFAULT 'School Pro Academy', "tagline" character varying, "address" character varying, "phone" character varying, "email" character varying, "website" character varying, "facebookPageUrl" character varying, "headmasterName" character varying, "logoUrl" character varying, "developerPhotoUrl" character varying, "currency" character varying NOT NULL DEFAULT 'USD', "studentIdPrefix" character varying(8) NOT NULL DEFAULT 'SP', "bankAccountName" character varying, "bankName" character varying, "bankBranch" character varying, "bankAccountNumber" character varying, "bankPaymentReferenceNote" text, "feeReminderTemplate" text, "gradeBoundaries" jsonb, "securityPolicy" jsonb, "integrationsConfig" jsonb, "notificationSettings" jsonb, "timetableVersion" character varying(32) NOT NULL DEFAULT '1', "minWeeklyPeriods" integer NOT NULL DEFAULT '0', "maxWeeklyPeriods" integer NOT NULL DEFAULT '30', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d0fcb46d187874b9f0e86c0941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school_fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(64) NOT NULL, "name" character varying NOT NULL, "description" character varying, "defaultAmount" numeric(12,2) NOT NULL DEFAULT '0', "icon" character varying(16), "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d17622202011fccb34c3ad09efb" UNIQUE ("code"), CONSTRAINT "PK_9945e05fd09ec4788110973650d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_promotion_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fromClassId" uuid NOT NULL, "toClassId" uuid, "completionLabel" character varying(128), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_eb28e31c2c47b917029917bcf83" UNIQUE ("fromClassId"), CONSTRAINT "PK_7d70088188583ee1ea609880511" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "results_publications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "termId" uuid NOT NULL, "examTypeId" uuid NOT NULL, "publishedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "publishedByUserId" uuid, "reportCardCount" integer NOT NULL DEFAULT '0', "whatsappSent" integer NOT NULL DEFAULT '0', "smsSent" integer NOT NULL DEFAULT '0', "notificationsCreated" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_b15be99cc27cc92eb39c28a4e3f" UNIQUE ("termId", "examTypeId"), CONSTRAINT "PK_894116f41ff750501e2a51f2561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_term_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "termId" uuid NOT NULL, "openingBalance" numeric(12,2) NOT NULL DEFAULT '0', "prepaidApplied" numeric(12,2) NOT NULL DEFAULT '0', "overpaymentPrepaid" numeric(12,2) NOT NULL DEFAULT '0', "overpaymentPrepaidApplied" numeric(12,2) NOT NULL DEFAULT '0', "carryForwardInvoiceId" uuid, "closingBalance" numeric(12,2), "initialized" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cce7d6a56bbd1a617dd44361b82" UNIQUE ("studentId", "termId"), CONSTRAINT "PK_3a02c73dc1fe101b3b10127ec99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."staff_payroll_profiles_payfrequency_enum" AS ENUM('monthly', 'biweekly')`);
        await queryRunner.query(`CREATE TYPE "public"."staff_payroll_profiles_paymentmethod_enum" AS ENUM('bank_transfer', 'cash', 'ecocash')`);
        await queryRunner.query(`CREATE TABLE "staff_payroll_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "staffId" uuid NOT NULL, "jobTitle" character varying, "payFrequency" "public"."staff_payroll_profiles_payfrequency_enum" NOT NULL DEFAULT 'monthly', "baseSalary" numeric(12,2) NOT NULL DEFAULT '0', "housingAllowance" numeric(12,2) NOT NULL DEFAULT '0', "transportAllowance" numeric(12,2) NOT NULL DEFAULT '0', "medicalAllowance" numeric(12,2) NOT NULL DEFAULT '0', "otherAllowances" numeric(12,2) NOT NULL DEFAULT '0', "payeAmount" numeric(12,2) NOT NULL DEFAULT '0', "nssaAmount" numeric(12,2) NOT NULL DEFAULT '0', "pensionAmount" numeric(12,2) NOT NULL DEFAULT '0', "loanDeduction" numeric(12,2) NOT NULL DEFAULT '0', "otherDeductions" numeric(12,2) NOT NULL DEFAULT '0', "bankName" character varying, "bankAccount" character varying, "bankBranch" character varying, "taxReference" character varying, "nssaNumber" character varying, "paymentMethod" "public"."staff_payroll_profiles_paymentmethod_enum" NOT NULL DEFAULT 'bank_transfer', "notes" text, "annualLeaveDays" numeric(6,2) NOT NULL DEFAULT '12', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b23432f1bc172fd5f351e6c981a" UNIQUE ("staffId"), CONSTRAINT "REL_b23432f1bc172fd5f351e6c981" UNIQUE ("staffId"), CONSTRAINT "PK_b5ab128831141ea8e22702444d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payroll_runs_status_enum" AS ENUM('draft', 'processed', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "payroll_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "year" integer NOT NULL, "month" integer NOT NULL, "periodLabel" character varying NOT NULL, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "payDate" date, "status" "public"."payroll_runs_status_enum" NOT NULL DEFAULT 'draft', "staffCount" integer NOT NULL DEFAULT '0', "totalGross" numeric(14,2) NOT NULL DEFAULT '0', "totalDeductions" numeric(14,2) NOT NULL DEFAULT '0', "totalNet" numeric(14,2) NOT NULL DEFAULT '0', "notes" text, "createdByUserId" character varying, "processedByUserId" character varying, "processedAt" TIMESTAMP WITH TIME ZONE, "paidByUserId" character varying, "paidAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ec4fac4dffe34e0bc9e2961f9db" UNIQUE ("reference"), CONSTRAINT "PK_6049f42c972640c0eb99ba8035e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payslips_paymentmethod_enum" AS ENUM('bank_transfer', 'cash', 'ecocash')`);
        await queryRunner.query(`CREATE TYPE "public"."payslips_status_enum" AS ENUM('pending', 'paid', 'excluded')`);
        await queryRunner.query(`CREATE TABLE "payslips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payrollRunId" uuid NOT NULL, "staffId" uuid NOT NULL, "employeeNumber" character varying NOT NULL, "staffName" character varying NOT NULL, "department" character varying, "jobTitle" character varying, "baseSalary" numeric(12,2) NOT NULL DEFAULT '0', "housingAllowance" numeric(12,2) NOT NULL DEFAULT '0', "transportAllowance" numeric(12,2) NOT NULL DEFAULT '0', "medicalAllowance" numeric(12,2) NOT NULL DEFAULT '0', "otherAllowances" numeric(12,2) NOT NULL DEFAULT '0', "grossPay" numeric(12,2) NOT NULL DEFAULT '0', "payeAmount" numeric(12,2) NOT NULL DEFAULT '0', "nssaAmount" numeric(12,2) NOT NULL DEFAULT '0', "pensionAmount" numeric(12,2) NOT NULL DEFAULT '0', "loanDeduction" numeric(12,2) NOT NULL DEFAULT '0', "otherDeductions" numeric(12,2) NOT NULL DEFAULT '0', "totalDeductions" numeric(12,2) NOT NULL DEFAULT '0', "netPay" numeric(12,2) NOT NULL DEFAULT '0', "paymentMethod" "public"."payslips_paymentmethod_enum" NOT NULL DEFAULT 'bank_transfer', "bankName" character varying, "bankAccount" character varying, "status" "public"."payslips_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "annualLeaveEntitlement" numeric(6,2) NOT NULL DEFAULT '12', "monthlyLeaveAccrual" numeric(6,2) NOT NULL DEFAULT '1', "leaveOpeningBalance" numeric(8,2) NOT NULL DEFAULT '0', "leaveTakenDays" numeric(6,2) NOT NULL DEFAULT '0', "leaveClosingBalance" numeric(8,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0d676236aa454b4685881a400f5" UNIQUE ("payrollRunId", "staffId"), CONSTRAINT "PK_2b1cd07059daf60cc440c9976e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_leave_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "staffId" uuid NOT NULL, "annualEntitlementDays" numeric(6,2) NOT NULL DEFAULT '12', "balanceDays" numeric(8,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_56f4a9a5d07f290cdefd3cf3ab8" UNIQUE ("staffId"), CONSTRAINT "REL_56f4a9a5d07f290cdefd3cf3ab" UNIQUE ("staffId"), CONSTRAINT "PK_7b69a272fc29a21c8b22ab79324" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tuition_exemptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "exemptionType" character varying(16) NOT NULL, "value" numeric(12,2) NOT NULL, "reason" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_999f7fb0b766f3e50f68e0b532e" UNIQUE ("studentId"), CONSTRAINT "PK_152243db13b3bac60a31755bd48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_adjustments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "noteNumber" character varying NOT NULL, "studentId" uuid NOT NULL, "type" character varying(16) NOT NULL, "amount" numeric(12,2) NOT NULL, "reason" text, "recordedById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f4b80839d3985bf72d340d6dad4" UNIQUE ("noteNumber"), CONSTRAINT "PK_4c311f559eecb3568514884f42d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chart_of_accounts_accounttype_enum" AS ENUM('REVENUE', 'EXPENSE', 'ASSET', 'LIABILITY', 'EQUITY')`);
        await queryRunner.query(`CREATE TABLE "chart_of_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountCode" character varying(32) NOT NULL, "accountName" character varying(128) NOT NULL, "accountType" "public"."chart_of_accounts_accounttype_enum" NOT NULL, "parentAccountId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4cb7d4663a389456682a1c4f359" UNIQUE ("accountCode"), CONSTRAINT "PK_467c08a2efc78393c647da32bac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_chart_of_accounts_type" ON "chart_of_accounts"  ("accountType") `);
        await queryRunner.query(`CREATE TYPE "public"."general_ledger_entries_referencetype_enum" AS ENUM('FEE_PAYMENT', 'SALARY', 'EXPENSE', 'REFUND', 'MANUAL_ADJUSTMENT', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "general_ledger_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transactionDate" date NOT NULL, "accountId" uuid NOT NULL, "debitAmount" numeric(14,2) NOT NULL DEFAULT '0', "creditAmount" numeric(14,2) NOT NULL DEFAULT '0', "description" text NOT NULL, "referenceType" "public"."general_ledger_entries_referencetype_enum" NOT NULL, "referenceId" uuid, "journalBatchId" uuid NOT NULL, "runningBalance" numeric(14,2) NOT NULL, "createdById" uuid NOT NULL, "isReversed" boolean NOT NULL DEFAULT false, "reversalOfEntryId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f503f1e8d18f677ee23f3aba633" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_gl_entry_journal_batch" ON "general_ledger_entries"  ("journalBatchId") `);
        await queryRunner.query(`CREATE INDEX "idx_gl_entry_reference_type" ON "general_ledger_entries"  ("referenceType") `);
        await queryRunner.query(`CREATE INDEX "idx_gl_entry_account_id" ON "general_ledger_entries"  ("accountId") `);
        await queryRunner.query(`CREATE INDEX "idx_gl_entry_transaction_date" ON "general_ledger_entries"  ("transactionDate") `);
        await queryRunner.query(`CREATE TABLE "application_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "docType" character varying(32) NOT NULL DEFAULT 'other', "originalName" character varying NOT NULL, "storedName" character varying NOT NULL, "mimeType" character varying NOT NULL, "sizeBytes" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_592142aa992e003beadf1409e9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referenceNumber" character varying NOT NULL, "studentFirstName" character varying NOT NULL, "studentLastName" character varying NOT NULL, "dateOfBirth" date, "gender" character varying(16), "previousSchool" character varying, "classAppliedFor" character varying NOT NULL, "guardianName" character varying NOT NULL, "guardianRelationship" character varying(64), "contactPhone" character varying NOT NULL, "contactEmail" character varying NOT NULL, "address" text, "status" character varying(32) NOT NULL DEFAULT 'applied', "statusNote" text, "reviewedAt" TIMESTAMP, "submittedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3ec039eea588b4eef34c68c30d5" UNIQUE ("referenceNumber"), CONSTRAINT "PK_938c0a27255637bde919591888f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bulk_message_recipients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bulkMessageId" uuid NOT NULL, "studentId" character varying, "userId" character varying, "recipientName" character varying NOT NULL, "recipientType" character varying(16) NOT NULL DEFAULT 'parent', "channel" character varying(16) NOT NULL, "destination" character varying, "status" character varying(16) NOT NULL, "error" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fce8e9ad6e41a5b86e375a5faf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bulk_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "senderId" uuid, "subject" character varying NOT NULL, "body" text NOT NULL, "channels" jsonb NOT NULL, "audience" jsonb, "audienceLabel" character varying, "totalRecipients" integer NOT NULL DEFAULT '0', "sentCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10f731203942bbbd35a25dcd448" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "student_enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "schoolYearId" uuid NOT NULL, "formId" character varying, "formName" character varying(120), "classId" character varying, "className" character varying(120), "status" character varying(24) NOT NULL DEFAULT 'enrolled', "startDate" date, "endDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_enrollment_student_year" UNIQUE ("studentId", "schoolYearId"), CONSTRAINT "PK_65f64fb270d4575b099b16e00a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3a870b3af82db9686a7349b49e" ON "student_enrollments"  ("studentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae8b7970fe3d24a932f1f58a02" ON "student_enrollments"  ("schoolYearId") `);
        await queryRunner.query(`CREATE TABLE "report_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "description" text, "config" jsonb NOT NULL, "createdById" character varying, "createdByName" character varying(160), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f85e16e6beea41a2b3a3350b84e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_715c95154a82c18adf7caec146" ON "report_templates"  ("name") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "userRole" character varying(32) NOT NULL, "userEmail" character varying(160), "action" character varying(16) NOT NULL, "module" character varying(64) NOT NULL, "recordId" character varying(64) NOT NULL, "recordLabel" character varying(255), "changes" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aca9ec48e47f56efca7d45898d" ON "audit_logs"  ("module") `);
        await queryRunner.query(`CREATE INDEX "IDX_5760b86e4062ff9507088c7410" ON "audit_logs"  ("recordId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs"  ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "record_book_columns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "termId" uuid NOT NULL, "classId" uuid NOT NULL, "subjectId" uuid NOT NULL, "ownerKey" character varying NOT NULL, "columnKey" character varying NOT NULL, "label" character varying NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e4589be60ff8c013258d790b84f" UNIQUE ("termId", "classId", "ownerKey", "subjectId", "columnKey"), CONSTRAINT "PK_062a621e8803e572223e0dce47a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "record_book_marks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "termId" uuid NOT NULL, "classId" uuid NOT NULL, "subjectId" uuid NOT NULL, "ownerKey" character varying NOT NULL, "studentId" uuid NOT NULL, "columnKey" character varying NOT NULL, "marks" numeric(6,2) NOT NULL, "enteredById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4ee1f826f58c6783d7cdb4041e2" UNIQUE ("termId", "classId", "ownerKey", "subjectId", "studentId", "columnKey"), CONSTRAINT "PK_24a394fca9bfc71fddeaf2a447e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "homework_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "subjectId" uuid, "termId" uuid NOT NULL, "teacherId" uuid NOT NULL, "title" character varying NOT NULL, "instructions" text, "originalFileName" character varying NOT NULL, "storedFileName" character varying NOT NULL, "mimeType" character varying NOT NULL, "fileSize" integer NOT NULL, "dueDate" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6e96c9e0467aa788a4ce9c81ac5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" uuid NOT NULL, "examId" uuid NOT NULL, "phone" character varying(32) NOT NULL, "messageSid" character varying(64), "status" character varying(24) NOT NULL DEFAULT 'queued', "errorMessage" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_19c524e644cdeaebfcffc284871" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lms_submissions_status_enum" AS ENUM('submitted', 'late', 'graded', 'returned')`);
        await queryRunner.query(`CREATE TABLE "lms_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assignmentId" uuid NOT NULL, "studentId" uuid NOT NULL, "textAnswer" text, "fileKey" character varying, "fileOriginalName" character varying, "fileMimeType" character varying, "fileSize" integer, "status" "public"."lms_submissions_status_enum" NOT NULL DEFAULT 'submitted', "grade" numeric(6,2), "feedback" text, "gradedById" uuid, "gradedAt" TIMESTAMP WITH TIME ZONE, "submittedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8a097345e6dbe9de35a365e07d3" UNIQUE ("assignmentId", "studentId"), CONSTRAINT "PK_6605ac08fa9938ff9d145babc48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ab3cfde9ec131bfa83f3c546d" ON "lms_submissions"  ("studentId", "submittedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."lms_assignments_status_enum" AS ENUM('draft', 'published', 'closed')`);
        await queryRunner.query(`CREATE TABLE "lms_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "subjectId" uuid, "termId" uuid, "teacherId" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "dueAt" TIMESTAMP WITH TIME ZONE, "maxScore" numeric(6,2), "status" "public"."lms_assignments_status_enum" NOT NULL DEFAULT 'draft', "attachmentKey" character varying, "attachmentOriginalName" character varying, "attachmentMimeType" character varying, "attachmentSize" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e5a93879e9067fdcf0497e80c14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eaf482b547674331d639fdcd8b" ON "lms_assignments"  ("classId", "subjectId", "dueAt") `);
        await queryRunner.query(`CREATE TYPE "public"."lesson_contents_contenttype_enum" AS ENUM('video', 'note', 'link', 'document', 'other')`);
        await queryRunner.query(`CREATE TABLE "lesson_contents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid, "subjectId" uuid NOT NULL, "termId" uuid, "uploadedById" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "contentType" "public"."lesson_contents_contenttype_enum" NOT NULL DEFAULT 'note', "externalUrl" text, "fileKey" character varying, "fileOriginalName" character varying, "fileMimeType" character varying, "fileSize" integer, "sortOrder" integer NOT NULL DEFAULT '0', "isPublished" boolean NOT NULL DEFAULT true, "publishedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d1b97652e81fe392bb9465cfb97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_585342a12e14b46e55a9dfbc95" ON "lesson_contents"  ("classId", "subjectId", "publishedAt") `);
        await queryRunner.query(`CREATE TABLE "class_recordings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "virtualClassId" uuid NOT NULL, "title" character varying NOT NULL, "recordingUrl" text NOT NULL, "fileKey" character varying, "durationSeconds" integer, "recordedAt" TIMESTAMP WITH TIME ZONE, "providerMeta" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920af09ed3694e5b6baf2d92106" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3818059a090a7bdf3b5c2a72a0" ON "class_recordings"  ("virtualClassId", "recordedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."virtual_classes_provider_enum" AS ENUM('manual', 'zoom', 'google_meet')`);
        await queryRunner.query(`CREATE TYPE "public"."virtual_classes_status_enum" AS ENUM('scheduled', 'live', 'ended', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "virtual_classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "classId" uuid NOT NULL, "subjectId" uuid, "teacherId" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "startsAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endsAt" TIMESTAMP WITH TIME ZONE, "provider" "public"."virtual_classes_provider_enum" NOT NULL DEFAULT 'manual', "status" "public"."virtual_classes_status_enum" NOT NULL DEFAULT 'scheduled', "joinUrl" text, "hostUrl" text, "externalMeetingId" character varying, "providerMeta" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a2e197e8cce2e9db74611929c77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2408276a3039d75b563b112bf6" ON "virtual_classes"  ("classId", "startsAt") `);
        await queryRunner.query(`CREATE TABLE "library_bookmarks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "resourceId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_69d7c64b84eaf9e4b5ae681c7ab" UNIQUE ("userId", "resourceId"), CONSTRAINT "PK_d416b62f9c8f3f5aa60009722e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."library_resources_resourcetype_enum" AS ENUM('book', 'pdf', 'video', 'audio', 'link', 'other')`);
        await queryRunner.query(`CREATE TABLE "library_resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "resourceType" "public"."library_resources_resourcetype_enum" NOT NULL DEFAULT 'pdf', "fileKey" character varying, "fileOriginalName" character varying, "fileMimeType" character varying, "fileSize" integer, "externalUrl" text, "subjectId" uuid, "gradeFormId" uuid, "uploadedById" uuid NOT NULL, "accessRoles" text array NOT NULL DEFAULT '{}', "isPublished" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4aa9381d621dc9c4a0ee28414f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_20dde58c2c181fcbf9c700a2c8" ON "library_resources"  ("gradeFormId", "resourceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc91dffe1c5b3e500595eb666a" ON "library_resources"  ("subjectId", "resourceType") `);
        await queryRunner.query(`ALTER TABLE "terms" ADD CONSTRAINT "FK_8ccf58120321db1b8293c4f3575" FOREIGN KEY ("schoolYearId") REFERENCES "school_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_eba76c23bcfc9dad2479b7fd2ad" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam_marks" ADD CONSTRAINT "FK_e34214919f1792e442f2d0fa960" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "exam_marks" ADD CONSTRAINT "FK_86700760cb9ac7402fe3d3dea3c" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "exam_marks" ADD CONSTRAINT "FK_140a53ccf0c4764d0047b77345d" FOREIGN KEY ("examTypeId") REFERENCES "exam_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "exam_marks" ADD CONSTRAINT "FK_0da709e1d21c8fe43b767efa0a0" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "exam_marks" ADD CONSTRAINT "FK_4d982a2b64efd504da2b8cdbe9c" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "exam_marks" ADD CONSTRAINT "FK_aec65752792a2fd730c933bb9ec" FOREIGN KEY ("enteredById") REFERENCES "staff"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "class_subjects" ADD CONSTRAINT "FK_ce7d61b2f3aa4ffc42b9bed8320" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "class_subjects" ADD CONSTRAINT "FK_0348e2a2a498046e21254b67463" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "class_subjects" ADD CONSTRAINT "FK_0b9687059594f0e01be7ee0e944" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sections" ADD CONSTRAINT "FK_94029a3f8836dbcba4cc01e4b8f" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_32db67d2461df0657741491659e" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_db018f5603d2552be9becf68690" FOREIGN KEY ("sectionId") REFERENCES "sections"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_dce424f97ffce384ac7ecc2c9d6" FOREIGN KEY ("classTeacherId") REFERENCES "staff"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "parents" ADD CONSTRAINT "FK_f1e08daeefd9c2e5def5746be7e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guardians" ADD CONSTRAINT "FK_c233a974fe6b0904c1d5ad05814" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "guardians" ADD CONSTRAINT "FK_1374928a84534c544bb88522622" FOREIGN KEY ("parentId") REFERENCES "parents"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student_attendance" ADD CONSTRAINT "FK_37db95ccd34d2f592c76006ff7f" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_9f57f31e620fe759b452feb776e" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_1a1d2f3a4c9d21b263ca8ff63e8" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2731e10aef7f886a08c552290e" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_43d19956aeab008b49e0804c145" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_6fd182b885ee75c7e0ba258062e" FOREIGN KEY ("recordedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_275c3d1cad7de2518d78dc81e52" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_c4344db2e1b1e6d6d385a927cb7" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_38745ab2a89e7570fdffbefa7f5" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" ADD CONSTRAINT "FK_6f35bea738c01c6dbbc84974cd4" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_e0208b4f964e609959aff431bf9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_575e5ce508ee1275f45cb7c4c32" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_caab744e496514ed53c5be0207e" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_78f504b571d5965ba9394480167" FOREIGN KEY ("schoolRoleId") REFERENCES "school_roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetables" ADD CONSTRAINT "FK_44303a910b5c68ad67e0262997c" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetables" ADD CONSTRAINT "FK_4233dafa78c507affb46a3500fe" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetables" ADD CONSTRAINT "FK_e7a92987b7b7b005c964c54eab8" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" ADD CONSTRAINT "FK_97723b08d3c43f7dbad902574de" FOREIGN KEY ("teacherAssignmentId") REFERENCES "teacher_assignments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" ADD CONSTRAINT "FK_b615c45b72d564e01f0726f312b" FOREIGN KEY ("timetableEntryId") REFERENCES "timetables"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teacher_assignments" ADD CONSTRAINT "FK_51c96ca1214fa55d9bec97a2ae2" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teacher_assignments" ADD CONSTRAINT "FK_0d00cb2869f4ca284ef64de11ce" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teacher_assignments" ADD CONSTRAINT "FK_427d60887e6ced5327bbf9b363b" FOREIGN KEY ("sectionId") REFERENCES "sections"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "teacher_assignments" ADD CONSTRAINT "FK_f0b413bb838d1a0e559a9e180ec" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staff_attendance" ADD CONSTRAINT "FK_0aed7c22a4e2c4b6fe6127af2f1" FOREIGN KEY ("staffId") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "report_cards" ADD CONSTRAINT "FK_435d59076f1c15d98035b7cd1dd" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "report_cards" ADD CONSTRAINT "FK_3aac028a5b97cc2784528054656" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "report_cards" ADD CONSTRAINT "FK_907e4fd1b6d2709e239c8d95933" FOREIGN KEY ("examTypeId") REFERENCES "exam_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "honour_rolls" ADD CONSTRAINT "FK_9ab5382927f13cfc722faf9b696" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "honour_rolls" ADD CONSTRAINT "FK_857494a3deb8b46e1e1b48cb070" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "honour_rolls" ADD CONSTRAINT "FK_457f163c725844c5432d3bad5c3" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cashbook_entries" ADD CONSTRAINT "FK_e5a0c0f8fc1b647e6bd458b7300" FOREIGN KEY ("recordedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_allocations" ADD CONSTRAINT "FK_0083a81104b9aae1f46e12cf55b" FOREIGN KEY ("timetableEntryId") REFERENCES "timetables"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_allocations" ADD CONSTRAINT "FK_5bb3ceefe353f7b352941002b5f" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_allocations" ADD CONSTRAINT "FK_9dbf95db253d3fa0441e5f6698b" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_allocations" ADD CONSTRAINT "FK_c7dcf61c69b7028e0d094716b59" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_schedules" ADD CONSTRAINT "FK_41c826eea13f27e705839a5e454" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_schedules" ADD CONSTRAINT "FK_e8f2d113bca206e512e924b6dee" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_schedules" ADD CONSTRAINT "FK_296bc0b9ca5afafbad6d8c9eb5a" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_schedules" ADD CONSTRAINT "FK_b502126f1df48dcea7b5480c7db" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_assessments" ADD CONSTRAINT "FK_d3e314f430baf986e951f9c826e" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_assessments" ADD CONSTRAINT "FK_dcc27a6f42995041b00eeb360db" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_assessments" ADD CONSTRAINT "FK_1f9620d75bd2e5ff06123fc92ed" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_assessments" ADD CONSTRAINT "FK_c761f9aafc9daa1d2bf9166c6f7" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_attachments" ADD CONSTRAINT "FK_5b4f24737fcb6b35ffdd4d16e13" FOREIGN KEY ("messageId") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_f548818d46a1315d4e1d5e62da5" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_e9d4215b1e3df68a5bd91d0363a" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tuckshop_sales" ADD CONSTRAINT "FK_50ff4f5c025612bc7c3177ae124" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tuckshop_sales" ADD CONSTRAINT "FK_586c8b92b8c39553853e35064c1" FOREIGN KEY ("itemId") REFERENCES "tuckshop_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uniform_sales" ADD CONSTRAINT "FK_cc51fdcb1d3cdd4a11f412429df" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_promotion_rules" ADD CONSTRAINT "FK_eb28e31c2c47b917029917bcf83" FOREIGN KEY ("fromClassId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "class_promotion_rules" ADD CONSTRAINT "FK_2b3a0b5bc8651f1a7b6b9fc07ea" FOREIGN KEY ("toClassId") REFERENCES "classes"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "results_publications" ADD CONSTRAINT "FK_01ef79b68feae5ab7b9620648fc" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "results_publications" ADD CONSTRAINT "FK_a58c047c60bfa832eba2c69b0df" FOREIGN KEY ("examTypeId") REFERENCES "exam_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "results_publications" ADD CONSTRAINT "FK_f6dbdb71f04026d85ba89075998" FOREIGN KEY ("publishedByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student_term_balances" ADD CONSTRAINT "FK_6957cfaea6cb1bc60058ae9bb9c" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_term_balances" ADD CONSTRAINT "FK_5508a5c50714a2db7c076f79b91" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_term_balances" ADD CONSTRAINT "FK_7799b5f9e715d7fbc31c7b5b55e" FOREIGN KEY ("carryForwardInvoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_payroll_profiles" ADD CONSTRAINT "FK_b23432f1bc172fd5f351e6c981a" FOREIGN KEY ("staffId") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payslips" ADD CONSTRAINT "FK_900143f20e6cd2fc0153db2242c" FOREIGN KEY ("payrollRunId") REFERENCES "payroll_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payslips" ADD CONSTRAINT "FK_a1171fbfe4c807c9f2d9cc88a7c" FOREIGN KEY ("staffId") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_leave_balances" ADD CONSTRAINT "FK_56f4a9a5d07f290cdefd3cf3ab8" FOREIGN KEY ("staffId") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tuition_exemptions" ADD CONSTRAINT "FK_999f7fb0b766f3e50f68e0b532e" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "invoice_adjustments" ADD CONSTRAINT "FK_dd94360751a0c0b30ddb7b09771" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" ADD CONSTRAINT "FK_3fc1730c76801339d6e545a2f18" FOREIGN KEY ("parentAccountId") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "general_ledger_entries" ADD CONSTRAINT "FK_eb8d5c47cdd19b64ddbfbcfb07a" FOREIGN KEY ("accountId") REFERENCES "chart_of_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "general_ledger_entries" ADD CONSTRAINT "FK_57fc1672d1228c7d1368b043401" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "general_ledger_entries" ADD CONSTRAINT "FK_3a3baa659cd8f067e1505b5019d" FOREIGN KEY ("reversalOfEntryId") REFERENCES "general_ledger_entries"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "application_documents" ADD CONSTRAINT "FK_fa1747f54494a479d3582aa9631" FOREIGN KEY ("applicationId") REFERENCES "applications"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bulk_message_recipients" ADD CONSTRAINT "FK_78cf83511855f57fdaa92776ab3" FOREIGN KEY ("bulkMessageId") REFERENCES "bulk_messages"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bulk_messages" ADD CONSTRAINT "FK_09150858fb2e5f6c0039b837f35" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student_enrollments" ADD CONSTRAINT "FK_3a870b3af82db9686a7349b49e7" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student_enrollments" ADD CONSTRAINT "FK_ae8b7970fe3d24a932f1f58a02e" FOREIGN KEY ("schoolYearId") REFERENCES "school_years"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "record_book_columns" ADD CONSTRAINT "FK_882e48098201029dd5005c88ff9" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "record_book_columns" ADD CONSTRAINT "FK_a492e26dfc2eed0713deb7b3e97" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "record_book_columns" ADD CONSTRAINT "FK_0bf620a90a30ef5a2ca61262ac2" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" ADD CONSTRAINT "FK_cc9fab5f603719acd33fa46a3eb" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" ADD CONSTRAINT "FK_a0744993548c21cc5f42fdc20a6" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" ADD CONSTRAINT "FK_616d7cef9c474249ac9e4fb9e4e" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" ADD CONSTRAINT "FK_cbc740579c767f6dcaccd66d23a" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" ADD CONSTRAINT "FK_101579b3a706a091608d92034b0" FOREIGN KEY ("enteredById") REFERENCES "staff"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD CONSTRAINT "FK_0f447fb1d7f8ba5df3299e72ee8" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD CONSTRAINT "FK_3d334ed18809944b35dd2a48063" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD CONSTRAINT "FK_a3e7ca2c209ec60a075cc741ae5" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD CONSTRAINT "FK_fc0e47344a66735d571f7b5cc7b" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ADD CONSTRAINT "FK_7f62453355000bdcfa5d5598d48" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_logs" ADD CONSTRAINT "FK_f67647b2864f2d29cdb6e0740d1" FOREIGN KEY ("examId") REFERENCES "exam_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lms_submissions" ADD CONSTRAINT "FK_4dddba492c9a4494d3bea95642e" FOREIGN KEY ("assignmentId") REFERENCES "lms_assignments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lms_submissions" ADD CONSTRAINT "FK_709313eccec7449da79f6bfee75" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lms_submissions" ADD CONSTRAINT "FK_1f585f7fa9a50502cc20ecc8cd6" FOREIGN KEY ("gradedById") REFERENCES "staff"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lms_assignments" ADD CONSTRAINT "FK_dce60abbee5feec0a3bb9d917cc" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lms_assignments" ADD CONSTRAINT "FK_91915abfa2474130d0f292765ce" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lms_assignments" ADD CONSTRAINT "FK_06ba1128d818b277bbcb6aca6e8" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lms_assignments" ADD CONSTRAINT "FK_9e2847e296184c27a21b30f11b7" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" ADD CONSTRAINT "FK_b4a7825494790779eca110d10a9" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" ADD CONSTRAINT "FK_de391eeccee5c177132c2c9306f" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" ADD CONSTRAINT "FK_779a43ccdb4768d421712ab35d3" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" ADD CONSTRAINT "FK_72fc63a9b91bb91939ba605c2ca" FOREIGN KEY ("uploadedById") REFERENCES "staff"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "class_recordings" ADD CONSTRAINT "FK_fd646492f8aff7d5ebce78bb81a" FOREIGN KEY ("virtualClassId") REFERENCES "virtual_classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "virtual_classes" ADD CONSTRAINT "FK_695ec9b2d1a6e8efa95c6bf1abe" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "virtual_classes" ADD CONSTRAINT "FK_d275141f5b8aa12bd77d0425ce2" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "virtual_classes" ADD CONSTRAINT "FK_8ec413b647e2437f487584b9559" FOREIGN KEY ("teacherId") REFERENCES "staff"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "library_bookmarks" ADD CONSTRAINT "FK_5bbabcb5d725153928f5068ad0e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "library_bookmarks" ADD CONSTRAINT "FK_fb157c101c83fc96e35d1e57278" FOREIGN KEY ("resourceId") REFERENCES "library_resources"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "library_resources" ADD CONSTRAINT "FK_db44ff3acefecad0113096573a3" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "library_resources" ADD CONSTRAINT "FK_ded2db5062f70d763a981e7fbf6" FOREIGN KEY ("gradeFormId") REFERENCES "forms"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "library_resources" ADD CONSTRAINT "FK_5c91f393634568d15b62e1ebb8a" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "library_resources" DROP CONSTRAINT "FK_5c91f393634568d15b62e1ebb8a"`);
        await queryRunner.query(`ALTER TABLE "library_resources" DROP CONSTRAINT "FK_ded2db5062f70d763a981e7fbf6"`);
        await queryRunner.query(`ALTER TABLE "library_resources" DROP CONSTRAINT "FK_db44ff3acefecad0113096573a3"`);
        await queryRunner.query(`ALTER TABLE "library_bookmarks" DROP CONSTRAINT "FK_fb157c101c83fc96e35d1e57278"`);
        await queryRunner.query(`ALTER TABLE "library_bookmarks" DROP CONSTRAINT "FK_5bbabcb5d725153928f5068ad0e"`);
        await queryRunner.query(`ALTER TABLE "virtual_classes" DROP CONSTRAINT "FK_8ec413b647e2437f487584b9559"`);
        await queryRunner.query(`ALTER TABLE "virtual_classes" DROP CONSTRAINT "FK_d275141f5b8aa12bd77d0425ce2"`);
        await queryRunner.query(`ALTER TABLE "virtual_classes" DROP CONSTRAINT "FK_695ec9b2d1a6e8efa95c6bf1abe"`);
        await queryRunner.query(`ALTER TABLE "class_recordings" DROP CONSTRAINT "FK_fd646492f8aff7d5ebce78bb81a"`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" DROP CONSTRAINT "FK_72fc63a9b91bb91939ba605c2ca"`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" DROP CONSTRAINT "FK_779a43ccdb4768d421712ab35d3"`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" DROP CONSTRAINT "FK_de391eeccee5c177132c2c9306f"`);
        await queryRunner.query(`ALTER TABLE "lesson_contents" DROP CONSTRAINT "FK_b4a7825494790779eca110d10a9"`);
        await queryRunner.query(`ALTER TABLE "lms_assignments" DROP CONSTRAINT "FK_9e2847e296184c27a21b30f11b7"`);
        await queryRunner.query(`ALTER TABLE "lms_assignments" DROP CONSTRAINT "FK_06ba1128d818b277bbcb6aca6e8"`);
        await queryRunner.query(`ALTER TABLE "lms_assignments" DROP CONSTRAINT "FK_91915abfa2474130d0f292765ce"`);
        await queryRunner.query(`ALTER TABLE "lms_assignments" DROP CONSTRAINT "FK_dce60abbee5feec0a3bb9d917cc"`);
        await queryRunner.query(`ALTER TABLE "lms_submissions" DROP CONSTRAINT "FK_1f585f7fa9a50502cc20ecc8cd6"`);
        await queryRunner.query(`ALTER TABLE "lms_submissions" DROP CONSTRAINT "FK_709313eccec7449da79f6bfee75"`);
        await queryRunner.query(`ALTER TABLE "lms_submissions" DROP CONSTRAINT "FK_4dddba492c9a4494d3bea95642e"`);
        await queryRunner.query(`ALTER TABLE "notification_logs" DROP CONSTRAINT "FK_f67647b2864f2d29cdb6e0740d1"`);
        await queryRunner.query(`ALTER TABLE "notification_logs" DROP CONSTRAINT "FK_7f62453355000bdcfa5d5598d48"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP CONSTRAINT "FK_fc0e47344a66735d571f7b5cc7b"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP CONSTRAINT "FK_a3e7ca2c209ec60a075cc741ae5"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP CONSTRAINT "FK_3d334ed18809944b35dd2a48063"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP CONSTRAINT "FK_0f447fb1d7f8ba5df3299e72ee8"`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" DROP CONSTRAINT "FK_101579b3a706a091608d92034b0"`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" DROP CONSTRAINT "FK_cbc740579c767f6dcaccd66d23a"`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" DROP CONSTRAINT "FK_616d7cef9c474249ac9e4fb9e4e"`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" DROP CONSTRAINT "FK_a0744993548c21cc5f42fdc20a6"`);
        await queryRunner.query(`ALTER TABLE "record_book_marks" DROP CONSTRAINT "FK_cc9fab5f603719acd33fa46a3eb"`);
        await queryRunner.query(`ALTER TABLE "record_book_columns" DROP CONSTRAINT "FK_0bf620a90a30ef5a2ca61262ac2"`);
        await queryRunner.query(`ALTER TABLE "record_book_columns" DROP CONSTRAINT "FK_a492e26dfc2eed0713deb7b3e97"`);
        await queryRunner.query(`ALTER TABLE "record_book_columns" DROP CONSTRAINT "FK_882e48098201029dd5005c88ff9"`);
        await queryRunner.query(`ALTER TABLE "student_enrollments" DROP CONSTRAINT "FK_ae8b7970fe3d24a932f1f58a02e"`);
        await queryRunner.query(`ALTER TABLE "student_enrollments" DROP CONSTRAINT "FK_3a870b3af82db9686a7349b49e7"`);
        await queryRunner.query(`ALTER TABLE "bulk_messages" DROP CONSTRAINT "FK_09150858fb2e5f6c0039b837f35"`);
        await queryRunner.query(`ALTER TABLE "bulk_message_recipients" DROP CONSTRAINT "FK_78cf83511855f57fdaa92776ab3"`);
        await queryRunner.query(`ALTER TABLE "application_documents" DROP CONSTRAINT "FK_fa1747f54494a479d3582aa9631"`);
        await queryRunner.query(`ALTER TABLE "general_ledger_entries" DROP CONSTRAINT "FK_3a3baa659cd8f067e1505b5019d"`);
        await queryRunner.query(`ALTER TABLE "general_ledger_entries" DROP CONSTRAINT "FK_57fc1672d1228c7d1368b043401"`);
        await queryRunner.query(`ALTER TABLE "general_ledger_entries" DROP CONSTRAINT "FK_eb8d5c47cdd19b64ddbfbcfb07a"`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" DROP CONSTRAINT "FK_3fc1730c76801339d6e545a2f18"`);
        await queryRunner.query(`ALTER TABLE "invoice_adjustments" DROP CONSTRAINT "FK_dd94360751a0c0b30ddb7b09771"`);
        await queryRunner.query(`ALTER TABLE "tuition_exemptions" DROP CONSTRAINT "FK_999f7fb0b766f3e50f68e0b532e"`);
        await queryRunner.query(`ALTER TABLE "staff_leave_balances" DROP CONSTRAINT "FK_56f4a9a5d07f290cdefd3cf3ab8"`);
        await queryRunner.query(`ALTER TABLE "payslips" DROP CONSTRAINT "FK_a1171fbfe4c807c9f2d9cc88a7c"`);
        await queryRunner.query(`ALTER TABLE "payslips" DROP CONSTRAINT "FK_900143f20e6cd2fc0153db2242c"`);
        await queryRunner.query(`ALTER TABLE "staff_payroll_profiles" DROP CONSTRAINT "FK_b23432f1bc172fd5f351e6c981a"`);
        await queryRunner.query(`ALTER TABLE "student_term_balances" DROP CONSTRAINT "FK_7799b5f9e715d7fbc31c7b5b55e"`);
        await queryRunner.query(`ALTER TABLE "student_term_balances" DROP CONSTRAINT "FK_5508a5c50714a2db7c076f79b91"`);
        await queryRunner.query(`ALTER TABLE "student_term_balances" DROP CONSTRAINT "FK_6957cfaea6cb1bc60058ae9bb9c"`);
        await queryRunner.query(`ALTER TABLE "results_publications" DROP CONSTRAINT "FK_f6dbdb71f04026d85ba89075998"`);
        await queryRunner.query(`ALTER TABLE "results_publications" DROP CONSTRAINT "FK_a58c047c60bfa832eba2c69b0df"`);
        await queryRunner.query(`ALTER TABLE "results_publications" DROP CONSTRAINT "FK_01ef79b68feae5ab7b9620648fc"`);
        await queryRunner.query(`ALTER TABLE "class_promotion_rules" DROP CONSTRAINT "FK_2b3a0b5bc8651f1a7b6b9fc07ea"`);
        await queryRunner.query(`ALTER TABLE "class_promotion_rules" DROP CONSTRAINT "FK_eb28e31c2c47b917029917bcf83"`);
        await queryRunner.query(`ALTER TABLE "uniform_sales" DROP CONSTRAINT "FK_cc51fdcb1d3cdd4a11f412429df"`);
        await queryRunner.query(`ALTER TABLE "tuckshop_sales" DROP CONSTRAINT "FK_586c8b92b8c39553853e35064c1"`);
        await queryRunner.query(`ALTER TABLE "tuckshop_sales" DROP CONSTRAINT "FK_50ff4f5c025612bc7c3177ae124"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_e9d4215b1e3df68a5bd91d0363a"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_f548818d46a1315d4e1d5e62da5"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "message_attachments" DROP CONSTRAINT "FK_5b4f24737fcb6b35ffdd4d16e13"`);
        await queryRunner.query(`ALTER TABLE "weekly_assessments" DROP CONSTRAINT "FK_c761f9aafc9daa1d2bf9166c6f7"`);
        await queryRunner.query(`ALTER TABLE "weekly_assessments" DROP CONSTRAINT "FK_1f9620d75bd2e5ff06123fc92ed"`);
        await queryRunner.query(`ALTER TABLE "weekly_assessments" DROP CONSTRAINT "FK_dcc27a6f42995041b00eeb360db"`);
        await queryRunner.query(`ALTER TABLE "weekly_assessments" DROP CONSTRAINT "FK_d3e314f430baf986e951f9c826e"`);
        await queryRunner.query(`ALTER TABLE "learning_schedules" DROP CONSTRAINT "FK_b502126f1df48dcea7b5480c7db"`);
        await queryRunner.query(`ALTER TABLE "learning_schedules" DROP CONSTRAINT "FK_296bc0b9ca5afafbad6d8c9eb5a"`);
        await queryRunner.query(`ALTER TABLE "learning_schedules" DROP CONSTRAINT "FK_e8f2d113bca206e512e924b6dee"`);
        await queryRunner.query(`ALTER TABLE "learning_schedules" DROP CONSTRAINT "FK_41c826eea13f27e705839a5e454"`);
        await queryRunner.query(`ALTER TABLE "teacher_allocations" DROP CONSTRAINT "FK_c7dcf61c69b7028e0d094716b59"`);
        await queryRunner.query(`ALTER TABLE "teacher_allocations" DROP CONSTRAINT "FK_9dbf95db253d3fa0441e5f6698b"`);
        await queryRunner.query(`ALTER TABLE "teacher_allocations" DROP CONSTRAINT "FK_5bb3ceefe353f7b352941002b5f"`);
        await queryRunner.query(`ALTER TABLE "teacher_allocations" DROP CONSTRAINT "FK_0083a81104b9aae1f46e12cf55b"`);
        await queryRunner.query(`ALTER TABLE "cashbook_entries" DROP CONSTRAINT "FK_e5a0c0f8fc1b647e6bd458b7300"`);
        await queryRunner.query(`ALTER TABLE "honour_rolls" DROP CONSTRAINT "FK_457f163c725844c5432d3bad5c3"`);
        await queryRunner.query(`ALTER TABLE "honour_rolls" DROP CONSTRAINT "FK_857494a3deb8b46e1e1b48cb070"`);
        await queryRunner.query(`ALTER TABLE "honour_rolls" DROP CONSTRAINT "FK_9ab5382927f13cfc722faf9b696"`);
        await queryRunner.query(`ALTER TABLE "report_cards" DROP CONSTRAINT "FK_907e4fd1b6d2709e239c8d95933"`);
        await queryRunner.query(`ALTER TABLE "report_cards" DROP CONSTRAINT "FK_3aac028a5b97cc2784528054656"`);
        await queryRunner.query(`ALTER TABLE "report_cards" DROP CONSTRAINT "FK_435d59076f1c15d98035b7cd1dd"`);
        await queryRunner.query(`ALTER TABLE "staff_attendance" DROP CONSTRAINT "FK_0aed7c22a4e2c4b6fe6127af2f1"`);
        await queryRunner.query(`ALTER TABLE "teacher_assignments" DROP CONSTRAINT "FK_f0b413bb838d1a0e559a9e180ec"`);
        await queryRunner.query(`ALTER TABLE "teacher_assignments" DROP CONSTRAINT "FK_427d60887e6ced5327bbf9b363b"`);
        await queryRunner.query(`ALTER TABLE "teacher_assignments" DROP CONSTRAINT "FK_0d00cb2869f4ca284ef64de11ce"`);
        await queryRunner.query(`ALTER TABLE "teacher_assignments" DROP CONSTRAINT "FK_51c96ca1214fa55d9bec97a2ae2"`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" DROP CONSTRAINT "FK_b615c45b72d564e01f0726f312b"`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" DROP CONSTRAINT "FK_97723b08d3c43f7dbad902574de"`);
        await queryRunner.query(`ALTER TABLE "timetables" DROP CONSTRAINT "FK_e7a92987b7b7b005c964c54eab8"`);
        await queryRunner.query(`ALTER TABLE "timetables" DROP CONSTRAINT "FK_4233dafa78c507affb46a3500fe"`);
        await queryRunner.query(`ALTER TABLE "timetables" DROP CONSTRAINT "FK_44303a910b5c68ad67e0262997c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_78f504b571d5965ba9394480167"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_caab744e496514ed53c5be0207e"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_575e5ce508ee1275f45cb7c4c32"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_e0208b4f964e609959aff431bf9"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_6f35bea738c01c6dbbc84974cd4"`);
        await queryRunner.query(`ALTER TABLE "ledger_entries" DROP CONSTRAINT "FK_38745ab2a89e7570fdffbefa7f5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_c4344db2e1b1e6d6d385a927cb7"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_275c3d1cad7de2518d78dc81e52"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_6fd182b885ee75c7e0ba258062e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_43d19956aeab008b49e0804c145"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2731e10aef7f886a08c552290e"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_1a1d2f3a4c9d21b263ca8ff63e8"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_9f57f31e620fe759b452feb776e"`);
        await queryRunner.query(`ALTER TABLE "student_attendance" DROP CONSTRAINT "FK_37db95ccd34d2f592c76006ff7f"`);
        await queryRunner.query(`ALTER TABLE "guardians" DROP CONSTRAINT "FK_1374928a84534c544bb88522622"`);
        await queryRunner.query(`ALTER TABLE "guardians" DROP CONSTRAINT "FK_c233a974fe6b0904c1d5ad05814"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP CONSTRAINT "FK_f1e08daeefd9c2e5def5746be7e"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_dce424f97ffce384ac7ecc2c9d6"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_db018f5603d2552be9becf68690"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_32db67d2461df0657741491659e"`);
        await queryRunner.query(`ALTER TABLE "sections" DROP CONSTRAINT "FK_94029a3f8836dbcba4cc01e4b8f"`);
        await queryRunner.query(`ALTER TABLE "class_subjects" DROP CONSTRAINT "FK_0b9687059594f0e01be7ee0e944"`);
        await queryRunner.query(`ALTER TABLE "class_subjects" DROP CONSTRAINT "FK_0348e2a2a498046e21254b67463"`);
        await queryRunner.query(`ALTER TABLE "class_subjects" DROP CONSTRAINT "FK_ce7d61b2f3aa4ffc42b9bed8320"`);
        await queryRunner.query(`ALTER TABLE "exam_marks" DROP CONSTRAINT "FK_aec65752792a2fd730c933bb9ec"`);
        await queryRunner.query(`ALTER TABLE "exam_marks" DROP CONSTRAINT "FK_4d982a2b64efd504da2b8cdbe9c"`);
        await queryRunner.query(`ALTER TABLE "exam_marks" DROP CONSTRAINT "FK_0da709e1d21c8fe43b767efa0a0"`);
        await queryRunner.query(`ALTER TABLE "exam_marks" DROP CONSTRAINT "FK_140a53ccf0c4764d0047b77345d"`);
        await queryRunner.query(`ALTER TABLE "exam_marks" DROP CONSTRAINT "FK_86700760cb9ac7402fe3d3dea3c"`);
        await queryRunner.query(`ALTER TABLE "exam_marks" DROP CONSTRAINT "FK_e34214919f1792e442f2d0fa960"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_eba76c23bcfc9dad2479b7fd2ad"`);
        await queryRunner.query(`ALTER TABLE "terms" DROP CONSTRAINT "FK_8ccf58120321db1b8293c4f3575"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc91dffe1c5b3e500595eb666a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20dde58c2c181fcbf9c700a2c8"`);
        await queryRunner.query(`DROP TABLE "library_resources"`);
        await queryRunner.query(`DROP TYPE "public"."library_resources_resourcetype_enum"`);
        await queryRunner.query(`DROP TABLE "library_bookmarks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2408276a3039d75b563b112bf6"`);
        await queryRunner.query(`DROP TABLE "virtual_classes"`);
        await queryRunner.query(`DROP TYPE "public"."virtual_classes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."virtual_classes_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3818059a090a7bdf3b5c2a72a0"`);
        await queryRunner.query(`DROP TABLE "class_recordings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_585342a12e14b46e55a9dfbc95"`);
        await queryRunner.query(`DROP TABLE "lesson_contents"`);
        await queryRunner.query(`DROP TYPE "public"."lesson_contents_contenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaf482b547674331d639fdcd8b"`);
        await queryRunner.query(`DROP TABLE "lms_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."lms_assignments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ab3cfde9ec131bfa83f3c546d"`);
        await queryRunner.query(`DROP TABLE "lms_submissions"`);
        await queryRunner.query(`DROP TYPE "public"."lms_submissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "notification_logs"`);
        await queryRunner.query(`DROP TABLE "homework_assignments"`);
        await queryRunner.query(`DROP TABLE "record_book_marks"`);
        await queryRunner.query(`DROP TABLE "record_book_columns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5760b86e4062ff9507088c7410"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aca9ec48e47f56efca7d45898d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_715c95154a82c18adf7caec146"`);
        await queryRunner.query(`DROP TABLE "report_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae8b7970fe3d24a932f1f58a02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a870b3af82db9686a7349b49e"`);
        await queryRunner.query(`DROP TABLE "student_enrollments"`);
        await queryRunner.query(`DROP TABLE "bulk_messages"`);
        await queryRunner.query(`DROP TABLE "bulk_message_recipients"`);
        await queryRunner.query(`DROP TABLE "applications"`);
        await queryRunner.query(`DROP TABLE "application_documents"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gl_entry_transaction_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gl_entry_account_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gl_entry_reference_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gl_entry_journal_batch"`);
        await queryRunner.query(`DROP TABLE "general_ledger_entries"`);
        await queryRunner.query(`DROP TYPE "public"."general_ledger_entries_referencetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chart_of_accounts_type"`);
        await queryRunner.query(`DROP TABLE "chart_of_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."chart_of_accounts_accounttype_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_adjustments"`);
        await queryRunner.query(`DROP TABLE "tuition_exemptions"`);
        await queryRunner.query(`DROP TABLE "staff_leave_balances"`);
        await queryRunner.query(`DROP TABLE "payslips"`);
        await queryRunner.query(`DROP TYPE "public"."payslips_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payslips_paymentmethod_enum"`);
        await queryRunner.query(`DROP TABLE "payroll_runs"`);
        await queryRunner.query(`DROP TYPE "public"."payroll_runs_status_enum"`);
        await queryRunner.query(`DROP TABLE "staff_payroll_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."staff_payroll_profiles_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."staff_payroll_profiles_payfrequency_enum"`);
        await queryRunner.query(`DROP TABLE "student_term_balances"`);
        await queryRunner.query(`DROP TABLE "results_publications"`);
        await queryRunner.query(`DROP TABLE "class_promotion_rules"`);
        await queryRunner.query(`DROP TABLE "school_fees"`);
        await queryRunner.query(`DROP TABLE "school_settings"`);
        await queryRunner.query(`DROP TABLE "uniform_sales"`);
        await queryRunner.query(`DROP TABLE "tuckshop_sales"`);
        await queryRunner.query(`DROP TABLE "tuckshop_items"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15f9bd2bf472ff12b6ee20012d"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "message_attachments"`);
        await queryRunner.query(`DROP TABLE "weekly_assessments"`);
        await queryRunner.query(`DROP TABLE "learning_schedules"`);
        await queryRunner.query(`DROP TABLE "teacher_allocations"`);
        await queryRunner.query(`DROP TYPE "public"."teacher_allocations_dayofweek_enum"`);
        await queryRunner.query(`DROP TABLE "cashbook_entries"`);
        await queryRunner.query(`DROP TYPE "public"."cashbook_entries_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cashbook_entries_type_enum"`);
        await queryRunner.query(`DROP TABLE "honour_rolls"`);
        await queryRunner.query(`DROP TABLE "report_cards"`);
        await queryRunner.query(`DROP TABLE "staff_attendance"`);
        await queryRunner.query(`DROP TYPE "public"."staff_attendance_status_enum"`);
        await queryRunner.query(`DROP TABLE "teacher_assignments"`);
        await queryRunner.query(`DROP TABLE "timetable_slots"`);
        await queryRunner.query(`DROP TABLE "timetables"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "school_roles"`);
        await queryRunner.query(`DROP TYPE "public"."school_roles_baserole_enum"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TABLE "ledger_entries"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "receipts"`);
        await queryRunner.query(`DROP TABLE "invoice_lines"`);
        await queryRunner.query(`DROP TABLE "student_attendance"`);
        await queryRunner.query(`DROP TYPE "public"."student_attendance_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."student_attendance_status_enum"`);
        await queryRunner.query(`DROP TABLE "guardians"`);
        await queryRunner.query(`DROP TABLE "parents"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TABLE "sections"`);
        await queryRunner.query(`DROP TABLE "class_subjects"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP TABLE "exam_marks"`);
        await queryRunner.query(`DROP TABLE "staff"`);
        await queryRunner.query(`DROP TABLE "terms"`);
        await queryRunner.query(`DROP TABLE "school_years"`);
        await queryRunner.query(`DROP TABLE "exam_types"`);
        await queryRunner.query(`DROP TYPE "public"."exam_types_code_enum"`);
        await queryRunner.query(`DROP TABLE "forms"`);
    }

}
